"""new fields in user model

Revision ID: 30672a4d42b4
Revises: 18f41d8b6fac
Create Date: 2019-03-27 11:27:21.162694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30672a4d42b4'
down_revision = '18f41d8b6fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
